# Generated by Django 4.2.4 on 2023-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
